name: advent_of_code
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  quiver: ^3.2.1
  timing: ^1.0.1

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0
